# Generated by Django 4.1.3 on 2022-11-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Darshan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='greetings_1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='greetings_2',
        ),
        migrations.AlterField(
            model_name='about',
            name='career',
            field=models.CharField(max_length=100),
        ),
    ]
